import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Typography,Button } from '@mui/material';
import NavBar from '@/components/NavBar';
import Header from '@/components/header';
import Footer from '@/components/Footer';
import Services from '@/components/Services';
import Subscribe from '@/components/Subscribe';
import Sponsors from '@/components/Sponsors';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Header/>
     
      <Sponsors/>
      <Subscribe/>
      <Services/>
      <Footer/>
    </>
  )
}
